### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by wangkaihong** [digitaldna01/CASCS506-FinalProject#1]
Hi,

The proposal is well-organized, and the motivation for the project looks interesting. However, for a data science class project, I am unsure if implementing a deep learning algorithm should be the highest priority. It would make more sense to me if you focus more on selecting a model, or compare to a few different models, even if they are implemented by some other packages, that match your goal of learning from the dataset you curate. You can further improve your model by transforming the data to better feed your model or increase the efficiency (e.g., using SVD to compress data, or transforming categorical data to numerical data for a regression model, etc.). To summarize, I believe the project can be a little more data-oriented.

**Comment by alicehan8** [comment]
Hi, 
Thank you for you feedback! We have implemented most of the changes you mentioned - namely removing the neural network and focusing more on comparing models and data compression techniques. We were a little curious whether we should entirely remove the neural network or if it could still be a part of the project, as I believe it is on the schedule as a topic for this course. Also, should we be implementing more of the models ourselves or is it ok if we are using mostly packages to compare these? Thank you again!

**Comment by wangkaihong** [comment]
Hi,

I'm sorry if I wasn't clear about my feedback. Including neural networks certainly helps, but I think you do not have to implement it (or SVM) from scratch, especially when you already have substantial work in plan to explore the performance of models for identifying cancer markers in genetic material. So, instead of 

> Our primary focus for this project will be to implement a neural network from scratch

,which I quote from your description of the project, you may focus more on the following part, 

> compare its performance against SVM and XGBoost models. By comparing the performance of various models, we can then draw a conclusion regarding which model is most appropriate for further cancer research in identifying cancer markers in DNA

And yes, it is OK for you to use packages since you have other focus.

**Comment by alicehan8** [comment]
Ok that makes sense thank you so much! Are you able to see our pull request? We have changed the project proposal to have more focus on comparing models, and it should be ready for you to review when you have a chance. Please let us know if there is anything else we should include. Thank you again!
